# Site settings
title: "Jesus, the Light of the World Arabic Church"
email: mokhles@abcatlanta.org
description: "We are an Arabic Baptist Church that meets in Lilburn, Georgia.  We love Jesus Christ and we love people."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: EA9643 #18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/groups/421427194628615/
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket 
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 285 Main Street
  - line: "Lilburn, Georgia 30047"

# Build settings
markdown: kramdown
permalink: pretty
